services:
  ###############################################################################
  # Gateway
  ###############################################################################
  gateway:
    environment:
      - RESETSERVICE_URL
    depends_on:
      - resetservice
  ###############################################################################
  # Authenticator
  ###############################################################################
  authenticator:
    environment:
      - MONGO_URL=mongodb://mongo/mredb_test
  ###############################################################################
  # PDFGenerator
  ###############################################################################
  pdfgenerator:
    environment:
      - MONGO_URL=mongodb://mongo/mredb_test
  ###############################################################################
  # Emailer
  ###############################################################################
  emailer:
    environment:
      - MONGO_URL=mongodb://mongo/mredb_test
  ###############################################################################
  # API
  ###############################################################################
  api:
    environment:
      - MONGO_URL=mongodb://mongo/mredb_test
  ###############################################################################
  # TenantAPI
  ###############################################################################
  tenantapi:
    environment:
      - MONGO_URL=mongodb://mongo/mredb_test
  ###############################################################################
  # ResetService
  ###############################################################################
  resetservice:
    restart: unless-stopped
    image: 'ghcr.io/microrealestate/microrealestate/resetservice:${MRE_VERSION:-latest}'
    build:
      context: .
      dockerfile: services/resetservice/Dockerfile
    environment:
      - NODE_ENV
      - PORT=$RESETSERVICE_PORT
      - LOGGER_LEVEL
      - REDIS_URL
      - REDIS_PASSWORD
      - MONGO_URL=mongodb://mongo/mredb_test
    expose:
      - "$RESETSERVICE_PORT"
    networks:
      - net
    depends_on:
      - redis
      - mongo
